// Auto generated by worker-postable
enum ENUM {
    HELLO,
    WORLD
}
class A {
    color: string;
    score: number;
}
abstract class ABS {
    abstract call();
}
class B {
    name;
    grade;
}
class C extends B {
    wheel;
}
class D<T> {
    hel() {
        console.log();
    }
}
class E extends D<number> {
    val: D<string>;
}
class A {
}
class B {
}
class C extends B {
}

export { ENUM as IENUM, A as IA, ABS as IABS, B as IB, C as IC, D as ID, E as IE, A as IA, B as IB, C as IC };
