// Auto generated by worker-postable
interface A {
    color: string;
    score: number;
}
interface B {
    name;
    grade;
}
interface C extends B {
    wheel;
}

export { A as IA, B as IB, C as IC };
