// Auto generated by worker-postable
class A {
    color: string;
    score: number;
}
class B {
    name;
    grade;
}
class C extends B {
    wheel;
}
class D<T> {
    hel() {
        console.log();
    }
}
class E extends D<number> {
    val: D<string>;
}
class A implements IA {
}
class B implements IB {
}
class C extends B implements IC {
}

export { A as IA, B as IB, C as IC, D as ID, E as IE, A as IA, B as IB, C as IC };
